spring:
    profiles:
        active: localhost
#        active: docker
server:
    port: 8080
    servlet:
        context-path: /fun-chat/api

---
spring:
    profiles: localhost
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${app.db.host}:${app.db.port}/${app.db.database}?schemas=${app.db.schema}
        username: ${app.db.username}
        password: ${app.db.password}
    jpa:
        hibernate.ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                default_schema: ${app.db.schema}
    flyway:
        enabled: true
        url: jdbc:postgresql://${app.db.host}:${app.db.port}/${app.db.database}?schemas=${app.db.schema}
        schemas: ${app.db.schema}
        locations: classpath:db/migration/${app.db.schema}
        user: ${app.db.username}
        password: ${app.db.password}
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: 44f6986519a443426742
                        client-secret: 51d7769f9d2b32d2a50fd446e5959b8ed4604b2b
                        redirect-uri: "{baseUrl}/login/oauth2/req/{registrationId}"
                    google:
                        clientId: 771267682052-bofb4v7ds7old3o2osf4j6nkmmhlkko3.apps.googleusercontent.com
                        clientSecret: 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
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - email
                            - profile
app:
    db:
        host: localhost
        port: 5432
        database: funchat
        schema: fc_local
        username: postgres
        password: 123456
    auth:
        tokenSecret: 04ca023b39512e46d0c2c739f38970518d5aac61d34302994c87ed4eff225dcf3b0a218a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1f4b4
        tokenExpirationMsec: 864000000
    cors:
        allowedOrigins: http://localhost:3000, http://localhost:8080
    oauth2:
        authorizedRedirectUris:
            - http://localhost:3000/oauth2/redirect

---
spring:
    profiles: docker
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${app.db.host}:${app.db.port}/${app.db.database}?schemas=${app.db.schema}
        username: ${app.db.username}
        password: ${app.db.password}
    jpa:
        hibernate.ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                default_schema: ${app.db.schema}
    flyway:
        enabled: true
        url: jdbc:postgresql://${app.db.host}:${app.db.port}/${app.db.database}?schemas=${app.db.schema}
        schemas: ${app.db.schema}
        locations: classpath:db/migration/${app.db.schema}
        user: ${app.db.username}
        password: ${app.db.password}
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: 44f6986519a443426742
                        client-secret: 51d7769f9d2b32d2a50fd446e5959b8ed4604b2b
                        redirect-uri: "{baseUrl}/login/oauth2/req/{registrationId}"
                    google:
                        clientId: 771267682052-bofb4v7ds7old3o2osf4j6nkmmhlkko3.apps.googleusercontent.com
                        clientSecret: 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
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - email
                            - profile
app:
    db:
        host: ec2-44-199-143-43.compute-1.amazonaws.com
        port: 5432
        database: dd9tkqb03fb9g7
        schema: fc_server
        username: prlokryqzvqrrb
        password: 4ae1019d1d5219491d59eafc77dfc817470b307cd56dbe8992ea8b7f7171f34b
    auth:
        tokenSecret: 04ca023b39512e46d0c2c739f38970518d5aac61d34302994c87ed4eff225dcf3b0a218a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1f4b4
        tokenExpirationMsec: 864000000
    cors:
        allowedOrigins: http://localhost:3000, http://localhost:8080
    oauth2:
        authorizedRedirectUris:
            - http://localhost:3000/oauth2/redirect